packages:
  - apps/*
  - packages/*

catalog:
  "@convex-dev/better-auth": ^0.9.11
  better-auth: ^1.4.9
  convex: ^1.31.2
  typescript: ^5.9.3

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
