/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as NewRouteImport } from './routes/new'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerRepoIndexRouteImport } from './routes/$owner/$repo/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as OwnerRepoGitUploadPackRouteImport } from './routes/$owner/$repo/git-upload-pack'
import { Route as OwnerRepoGitReceivePackRouteImport } from './routes/$owner/$repo/git-receive-pack'
import { Route as OwnerRepoInfoRefsRouteImport } from './routes/$owner/$repo/info/refs'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoIndexRoute = OwnerRepoIndexRouteImport.update({
  id: '/$owner/$repo/',
  path: '/$owner/$repo/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoGitUploadPackRoute = OwnerRepoGitUploadPackRouteImport.update({
  id: '/$owner/$repo/git-upload-pack',
  path: '/$owner/$repo/git-upload-pack',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoGitReceivePackRoute = OwnerRepoGitReceivePackRouteImport.update({
  id: '/$owner/$repo/git-receive-pack',
  path: '/$owner/$repo/git-receive-pack',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoInfoRefsRoute = OwnerRepoInfoRefsRouteImport.update({
  id: '/$owner/$repo/info/refs',
  path: '/$owner/$repo/info/refs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/new': typeof NewRoute
  '/todos': typeof TodosRoute
  '/$owner/$repo/git-receive-pack': typeof OwnerRepoGitReceivePackRoute
  '/$owner/$repo/git-upload-pack': typeof OwnerRepoGitUploadPackRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$owner/$repo': typeof OwnerRepoIndexRoute
  '/$owner/$repo/info/refs': typeof OwnerRepoInfoRefsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/new': typeof NewRoute
  '/todos': typeof TodosRoute
  '/$owner/$repo/git-receive-pack': typeof OwnerRepoGitReceivePackRoute
  '/$owner/$repo/git-upload-pack': typeof OwnerRepoGitUploadPackRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$owner/$repo': typeof OwnerRepoIndexRoute
  '/$owner/$repo/info/refs': typeof OwnerRepoInfoRefsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/new': typeof NewRoute
  '/todos': typeof TodosRoute
  '/$owner/$repo/git-receive-pack': typeof OwnerRepoGitReceivePackRoute
  '/$owner/$repo/git-upload-pack': typeof OwnerRepoGitUploadPackRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/$owner/$repo/info/refs': typeof OwnerRepoInfoRefsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/new'
    | '/todos'
    | '/$owner/$repo/git-receive-pack'
    | '/$owner/$repo/git-upload-pack'
    | '/api/auth/$'
    | '/$owner/$repo'
    | '/$owner/$repo/info/refs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/new'
    | '/todos'
    | '/$owner/$repo/git-receive-pack'
    | '/$owner/$repo/git-upload-pack'
    | '/api/auth/$'
    | '/$owner/$repo'
    | '/$owner/$repo/info/refs'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/new'
    | '/todos'
    | '/$owner/$repo/git-receive-pack'
    | '/$owner/$repo/git-upload-pack'
    | '/api/auth/$'
    | '/$owner/$repo/'
    | '/$owner/$repo/info/refs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  NewRoute: typeof NewRoute
  TodosRoute: typeof TodosRoute
  OwnerRepoGitReceivePackRoute: typeof OwnerRepoGitReceivePackRoute
  OwnerRepoGitUploadPackRoute: typeof OwnerRepoGitUploadPackRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  OwnerRepoIndexRoute: typeof OwnerRepoIndexRoute
  OwnerRepoInfoRefsRoute: typeof OwnerRepoInfoRefsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/': {
      id: '/$owner/$repo/'
      path: '/$owner/$repo'
      fullPath: '/$owner/$repo'
      preLoaderRoute: typeof OwnerRepoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/git-upload-pack': {
      id: '/$owner/$repo/git-upload-pack'
      path: '/$owner/$repo/git-upload-pack'
      fullPath: '/$owner/$repo/git-upload-pack'
      preLoaderRoute: typeof OwnerRepoGitUploadPackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/git-receive-pack': {
      id: '/$owner/$repo/git-receive-pack'
      path: '/$owner/$repo/git-receive-pack'
      fullPath: '/$owner/$repo/git-receive-pack'
      preLoaderRoute: typeof OwnerRepoGitReceivePackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/info/refs': {
      id: '/$owner/$repo/info/refs'
      path: '/$owner/$repo/info/refs'
      fullPath: '/$owner/$repo/info/refs'
      preLoaderRoute: typeof OwnerRepoInfoRefsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  NewRoute: NewRoute,
  TodosRoute: TodosRoute,
  OwnerRepoGitReceivePackRoute: OwnerRepoGitReceivePackRoute,
  OwnerRepoGitUploadPackRoute: OwnerRepoGitUploadPackRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  OwnerRepoIndexRoute: OwnerRepoIndexRoute,
  OwnerRepoInfoRefsRoute: OwnerRepoInfoRefsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
